// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3j7JOcT8TYjyXaamjqZsLKZbtNbUPyDQ',
    appId: '1:546647555698:web:4a7097bdf51497c424cceb',
    messagingSenderId: '546647555698',
    projectId: 'flutter-app-87d2c',
    authDomain: 'flutter-app-87d2c.firebaseapp.com',
    storageBucket: 'flutter-app-87d2c.appspot.com',
    measurementId: 'G-X8W22V7SY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcdimE4oJUkj4-gk7HAEKWWJYBdmIoNQo',
    appId: '1:546647555698:android:01b9cf1fc4b611c524cceb',
    messagingSenderId: '546647555698',
    projectId: 'flutter-app-87d2c',
    storageBucket: 'flutter-app-87d2c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApXAHDIfKWJ9dKozEJAerr08HCao8qoHU',
    appId: '1:546647555698:ios:ac6fdcacc969ff5a24cceb',
    messagingSenderId: '546647555698',
    projectId: 'flutter-app-87d2c',
    storageBucket: 'flutter-app-87d2c.appspot.com',
    androidClientId: '546647555698-p96hr5bf23kftu6mv0gpumjoqhafbb81.apps.googleusercontent.com',
    iosClientId: '546647555698-dpg633aagss8t54sul4c8l5mt8hdlfrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3j7JOcT8TYjyXaamjqZsLKZbtNbUPyDQ',
    appId: '1:546647555698:web:49650dcacc7e55cd24cceb',
    messagingSenderId: '546647555698',
    projectId: 'flutter-app-87d2c',
    authDomain: 'flutter-app-87d2c.firebaseapp.com',
    storageBucket: 'flutter-app-87d2c.appspot.com',
    measurementId: 'G-KR02NSJVY2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApXAHDIfKWJ9dKozEJAerr08HCao8qoHU',
    appId: '1:546647555698:ios:2f45bd65ad267e8c24cceb',
    messagingSenderId: '546647555698',
    projectId: 'flutter-app-87d2c',
    storageBucket: 'flutter-app-87d2c.appspot.com',
    androidClientId: '546647555698-p96hr5bf23kftu6mv0gpumjoqhafbb81.apps.googleusercontent.com',
    iosClientId: '546647555698-3cij09bkljt12ar5ospgq3v8h2g3r62a.apps.googleusercontent.com',
    iosBundleId: 'com.fabiodom.flutterapp',
  );

}